services:
  valkey:
    image: valkey/valkey:9.1-alpine
    networks:
      - evolution-net
    container_name: valkey
    command: >
      valkey-server --port 6379 --appendonly yes
    volumes:
      - evolution_valkey:/data
    ports:
      - 6379:6379

volumes:
  evolution_valkey:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
